target 'iosApp' do
  source 'https://cdn.cocoapods.org'
  use_frameworks!
  platform :ios, '14.1'
  pod 'shared', :path => '../shared'

  post_install do |installer|
     installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
     end
    end
end
